### ISSUE TITLE
Formulate a numerical scheme for laser calculation in 3D

### ISSUE THREAD

**Issue by kargapolov** [lcodePy-team/lcodePy#17]
Should ask Roman and Irina and discuss and write the numerical scheme. Roman and Ivan are supervising. I propose to simultaneously write the scheme in latex here for quick transfer to any necessary documents later.

Deadline: I suggest striving to complete this task in 4 weeks, so the deadline is October 10th.

**Comment by marrrrrry2001** [comment]
I sent a pdf file with a numerical scheme.

[KURS_laser.pdf](https://github.com/lcodePy-team/lcodePy/files/9626008/KURS_laser.pdf)

**Comment by kargapolov** [comment]
Roman had come up with an idea to add the Crank-Nicholson method to the calculation of laser evolution, and we decided to add it later.

**Comment by kargapolov** [comment]
We've found several problems with RHS in the numerical scheme; we intend to address them and improve the scheme.

**Comment by marrrrrry2001** [comment]
Version with corrected RHS.

[scheme.pdf](https://github.com/lcodePy-team/lcodePy/files/9876441/scheme.pdf)
